-- MODIFY COLUMN – Position
USE STUDENTDB;
SELECT * FROM STUDENTS;
DESC STUDENTS;
ALTER TABLE STUDENTS MODIFY EMAIL varchar(50) FIRST;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
DESC EMPLOYEES;
ALTER TABLE EMPLOYEES MODIFY SALARY decimal(15,2) AFTER JOB_ROLE;

USE HOSPITALDB;
SELECT * FROM PATIENTS;
DESC PATIENTS;
ALTER TABLE PATIENTS MODIFY BLOOD_GROUP varchar(5) FIRST;

USE LIBRARYDB;
SELECT * FROM BOOKS;
DESC BOOKS;
ALTER TABLE BOOKS MODIFY PRICE decimal(15,2) AFTER BOOK_NAME;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
DESC PRODUCTS;
ALTER TABLE PRODUCTS MODIFY BRAND varchar(50) AFTER PRODUCT_NAME;

USE COLLEGEDB;
SELECT * FROM COURSES;
DESC COURSES;
ALTER TABLE COURSES MODIFY FEES decimal(10,2) AFTER DURATION;

-- MODIFY COLUMN – Data Type / Size
USE STUDENTDB;
DESC STUDENTS;
ALTER TABLE STUDENTS MODIFY STUDENT_NAME varchar(100);

USE EMPLOYEEDB;
DESC EMPLOYEES;
ALTER TABLE EMPLOYEES MODIFY EMPLOYEE_NAME varchar(100);

USE HOSPITALDB;
DESC PATIENTS;
ALTER TABLE PATIENTS MODIFY PHONE varchar(20);

USE LIBRARYDB;
DESC BOOKS;
ALTER TABLE BOOKS MODIFY BOOK_NAME varchar(150);

USE SHOPPINGDB;
DESC PRODUCTS;
ALTER TABLE PRODUCTS MODIFY PRICE decimal(10,2);

USE BANKDB;
DESC ACCOUNTS;
ALTER TABLE ACCOUNTS MODIFY BALANCE decimal(15,2);

-- MODIFY COLUMN – Data Type + Position
USE STUDENTDB;
SELECT * FROM STUDENTS;
DESC STUDENTS;
ALTER TABLE STUDENTS MODIFY EMAIL varchar(150);
ALTER TABLE STUDENTS MODIFY EMAIL VARCHAR(150) AFTER STUDENT_NAME;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
DESC EMPLOYEES;
ALTER TABLE EMPLOYEES MODIFY DEPARTMENT varchar(100);
ALTER TABLE EMPLOYEES MODIFY DEPARTMENT varchar(100) AFTER EMPLOYEE_NAME;

USE MOVIEDB;
SELECT * FROM MOVIES;
DESC MOVIES;
ALTER TABLE MOVIES MODIFY RATING DECIMAL(3,1);
ALTER TABLE MOVIES MODIFY RATING DECIMAL(3,1) AFTER MOVIE_NAME;

USE HOTELDB;
SELECT * FROM ROOMS;
DESC ROOMS;
ALTER TABLE ROOMS MODIFY ROOM_NUMBER varchar(10);
ALTER TABLE ROOMS MODIFY ROOM_NUMBER varchar(10) FIRST;

-- RENAME COLUMN
USE STUDENTDB;
DESC STUDENTS;
ALTER TABLE STUDENTS RENAME COLUMN PHONE TO MOBILE_NUMBER;

USE EMPLOYEEDB;
DESC EMPLOYEES;
ALTER TABLE EMPLOYEES RENAME COLUMN JOB_ROLE TO DESIGNATION;

USE LIBRARYDB;
DESC BOOKS;
ALTER TABLE BOOKS RENAME COLUMN BOOK_NAME TO TITLE;

USE MOVIEDB;
DESC MOVIES;
ALTER TABLE MOVIES RENAME COLUMN MOVIE_NAME TO TITLE;

USE SHOPPINGDB;
DESC PRODUCTS;
ALTER TABLE PRODUCTS RENAME COLUMN STOCK_QUANTITY TO AVAILABLE_STOCK;

USE ECOMMERCEDB;
DESC CUSTOMERS;
ALTER TABLE CUSTOMERS RENAME COLUMN REGISTRATION_DATE TO REGISTERED_DATE;

-- ADD COLUMN
USE STUDENTDB;
DESC STUDENTS;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS ADD COLUMN DATEOFBIRTH VARCHAR(15);

USE EMPLOYEEDB;
DESC EMPLOYEES;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES ADD COLUMN EMAIL VARCHAR(50);

USE HOSPITALDB;
DESC PATIENTS;
SELECT * FROM PATIENTS;
ALTER TABLE PATIENTS ADD COLUMN DOCTOR_NAME VARCHAR(50);

USE SHOPPINGDB;
DESC PRODUCTS;
SELECT * FROM PRODUCTS;
ALTER TABLE PRODUCTS ADD COLUMN DISCOUNT DECIMAL(5,2);

USE MOVIEDB;
DESC MOVIES;
SELECT * FROM MOVIES;
ALTER TABLE MOVIES ADD COLUMN DIRECTOR_NAME VARCHAR(50);

-- DROP COLUMN 
USE STUDENTDB;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS DROP COLUMN GENDER;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES DROP COLUMN DATEOFBIRTH;

USE HOTELDB;
SELECT * FROM ROOMS;
ALTER TABLE ROOMS DROP COLUMN FLOOR_NUMBER;