USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE MOVIEDB;
USE HOTELDB;
USE ECOMMERCEDB;

-- ANY
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='HR');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='IT');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY = ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='FINANCE');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ELECTRONICS');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE < ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ACCESSORIES');
SELECT TITLE FROM BOOKS WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT TITLE FROM BOOKS WHERE PRICE < ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY='SCIENCE');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='IT');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE < ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='CSE');
SELECT COURSE_NAME FROM COURSES WHERE FEES > ANY (SELECT FEES FROM COURSES WHERE DEPARTMENT='IT'); 
SELECT COURSE_NAME FROM COURSES WHERE FEES < ANY (SELECT FEES FROM COURSES WHERE DEPARTMENT='CSE');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION='DEVELOPER');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE BRAND='SAMSUNG');
SELECT TITLE FROM BOOKS WHERE QUANTITY > ANY (SELECT QUANTITY FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT PATIENT_NAME FROM PATIENTS WHERE AGE > ANY (SELECT AGE FROM PATIENTS WHERE DISEASE='FEVER');

-- ALL
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='HR');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='IT');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY = ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='FINANCE');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ELECTRONICS');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE < ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ACCESSORIES');
SELECT TITLE FROM BOOKS WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT TITLE FROM BOOKS WHERE PRICE < ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY='SCIENCE');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='IT');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE < ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='CSE');
SELECT COURSE_NAME FROM COURSES WHERE FEES > ALL (SELECT FEES FROM COURSES WHERE DEPARTMENT='IT'); 
SELECT COURSE_NAME FROM COURSES WHERE FEES < ALL (SELECT FEES FROM COURSES WHERE DEPARTMENT='CSE');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION='DEVELOPER');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE BRAND='SAMSUNG');
SELECT TITLE FROM BOOKS WHERE QUANTITY > ALL (SELECT QUANTITY FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT PATIENT_NAME FROM PATIENTS WHERE AGE > ALL (SELECT AGE FROM PATIENTS WHERE DISEASE='FEVER');

-- Mixed ANY and ALL
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='HR');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT='HR');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE < ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ELECTRONICS');
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE < ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY='ELECTRONICS');
SELECT TITLE FROM BOOKS WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT TITLE FROM BOOKS WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY='TECHNOLOGY');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='CSE');
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT='CSE');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION='DEVELOPER');
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION='DEVELOPER');