SELECT STUDENT_NAME, AGE,
CASE
WHEN AGE >= 18 THEN 'MAJOR'
ELSE 'MINOR'
END AS AGE_CATEGORY
FROM STUDENTS ORDER BY AGE DESC;

SELECT EMPLOYEE_NAME, SALARY, 
CASE
WHEN SALARY >= 60000 THEN 'HIGH'
WHEN SALARY >= 40000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEES;

SELECT STUDENT_NAME, MARKS,
CASE
WHEN MARKS >= 90 THEN 'EXCELLENT'
WHEN MARKS BETWEEN 75 AND 89 THEN 'VERY GOOD'
WHEN MARKS BETWEEN 50 AND 74 THEN 'GOOD'
ELSE 'FAIL'
END AS MARKS_CATEGORY
FROM STUDENTS;

SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >=50000 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY
FROM EMPLOYEES;

SELECT PRODUCT_NAME, PRICE,
CASE
WHEN PRICE >= 50000 THEN 'EXPENSIVE'
WHEN PRICE >= 10000 THEN 'MODERATE'
ELSE 'AFFORDABLE'
END AS PRODUCT_CATEGORIZATION
FROM PRODUCTS;

SELECT TITLE, PRICE,
CASE
WHEN PRICE >= 1000 THEN 'PREMIUM'
ELSE 'REGULAR'
END AS BOOK_CATEGORIZATION
FROM BOOKS;

SELECT PATIENT_NAME, AGE,
CASE
WHEN AGE >= 60 THEN 'SENIOR CITIZEN'
WHEN AGE >= 18 THEN 'ADULT'
ELSE 'MINOR'
END AS AGE_CATEGORIZATION
FROM PATIENTS;

SELECT EMPLOYEE_NAME, EXPERIENCE,
CASE
WHEN EXPERIENCE >= 10 THEN 'SENIOR'
WHEN EXEPERIENCE >= 5 THEN 'INTERMEDIATE'
ELSE 'JUNIOR'
END AS EXPERIENCE_CATEGORIZATION
FROM EMPLOYEES;

SELECT COURSE_NAME, FEES,
CASE
WHEN FEES >= 50000 THEN 'HIGH FEES'
WHEN FEES >= 30000 THEN 'MEDIUM FEES'
ELSE 'LOW FEES'
END AS FEES_CATEGORY
FROM COURSES;

SELECT PRODUCT_NAME, AVAILABLE_STOCK,
CASE
WHEN AVAILABLE_STOCK = 0 THEN 'OUT OF STOCK'
WHEN AVAILABLE_STOCK < 10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS STOCK_AVAILABILITY
FROM PRODUCTS;

SELECT STUDENT_NAME, MARKS,
CASE
WHEN MARKS >= 40 THEN 'PASS'
ELSE 'FAIL'
END AS RANKING
FROM STUDENTS;

SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >= 70000 THEN 'HIGH SALARY'
ELSE 'LOW SALARY'
END AS EMPLOYEE_SALARY
FROM EMPLOYEES;

SELECT TITLE, PRICE,
CASE
WHEN PRICE >= 1500 THEN 'COSTLY'
ELSE 'AFFORDABLE'
END AS BOOKS_CATEGORIZATION
FROM BOOKS;

SELECT PRODUCT_NAME, QUANTITY,
CASE
WHEN QUANTITY >= 100 THEN 'BULK'
ELSE 'NORMAL'
END AS QUANTITY_CATEGORIZATION
FROM PRODUCTS;

SELECT TITLE, RATING,
CASE 
WHEN RATING >= 4.5 THEN 'EXCELLENT' 
WHEN RATING >= 3 THEN 'GOOD' 
ELSE 'AVERAGE'
END AS RATING_CATEGORIZATION
FROM MOVIES;

SELECT CUSTOMER_NAME, AGE,
CASE 
WHEN AGE >= 60 THEN 'SENIOR'
WHEN AGE >= 18 THEN 'ADULT'
ELSE 'YOUNG'
END AS AGE_CATEGORIZATION
FROM CUSTOMERS;

SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >= 75000 THEN 'GRADE A'
WHEN SALARY >= 50000 THEN 'GRADE B'
ELSE 'GRADE C'
END AS GRADE
FROM EMPLOYEES;

SELECT STUDENT_NAME, ATTENDANCE,
CASE
WHEN ATTENDANCE >= 90 THEN 'EXCELLENT'
WHEN ATTENDANCE >= 75 THEN 'GOOD'
ELSE 'LOW'
END AS ATTENDANCE_PERCENTAGE
FROM STUDENTS;

SELECT PRODUCT_NAME, PRICE,
CASE
WHEN PRICE >= 100000 THEN 'LUXURY'
WHEN PRICE >= 50000 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS PRICING
FROM PRODUCTS;

SELECT COURSE_NAME, DURATION,
CASE
WHEN DURATION >= 12 THEN 'LONG TERM'
WHEN DURATION >= 6 THEN 'MEDIUM TERM'
ELSE 'SHORT TERM'
END AS DURATION_TERM
FROM COURSES;

-- CASE WITH MULTIPLE CONDITIONS
USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY, DEPARTMENT,
CASE
WHEN DEPARTMENT='IT' AND SALARY >=60000 THEN 'IT HIGH SALARY'
WHEN DEPARTMENT='HR' AND SALARY >=50000 THEN 'HR HIGH SALARY'
ELSE 'OTHERS'
END AS HIGH_SALARY
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, DEPARTMENT, MARKS,
CASE
WHEN DEPARTMENT='CSE' AND MARKS >= 80 THEN 'CSE EXCELLENT'
WHEN DEPARTMENT='IT' AND MARKS >= 80 THEN 'IT EXCELLENT'
ELSE 'OTHERS'
END AS MARK_CAT
FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, PRICE, CATEGORY, 
CASE
WHEN CATEGORY='ELECTRONICS' AND PRICE >= 50000 THEN 'PREMIUM'
WHEN CATEGORY='ELECTRONICS' AND PRICE < 50000 THEN 'REGULAR'
ELSE 'OTHERS'
END AS PRODUCT_CAT
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY, EXPERIENCE,
CASE
WHEN SALARY >= 70000 AND EXPERIENCE >= 5 THEN 'SENIOR HIGH SALARY'
WHEN SALARY < 50000 THEN 'GOOD'
ELSE 'REGULAR'
END AS EXP_EMPLOYEE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, AGE, ATTENDANCE,
CASE
WHEN AGE >= 18 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS ATTENDANCE_STU
FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, AVAILABLE_STOCK,
CASE
WHEN AVAILABLE_STOCK = 0 THEN 'OUT OF STOCK'
WHEN AVAILABLE_STOCK < 10 THEN 'LOW STOCK'
WHEN AVAILABLE_STOCK >= 10 THEN 'AVAILABLE'
END AS STOCK_AVAILABILITY
FROM PRODUCTS;

USE MOVIEDB;
SELECT TITLE, RATING, LANGUAGE,
CASE
WHEN RATING >= 4.5 AND LANGUAGE='TAMIL' THEN 'TAMIL HIT'
WHEN RATING >= 4.5 THEN 'HIT'
ELSE 'AVERAGE'
END AS MOVIE_RATING
FROM MOVIES;

USE LIBRARYDB;
SELECT TITLE, PRICE, CATEGORY,
CASE
WHEN CATEGORY='TECHNOLOGY' AND PRICE >1500 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS PREMIUM_BOOKS
FROM BOOKS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY, DEPARTMENT,
CASE
WHEN SALARY > 60000 AND DEPARTMENT='IT' THEN 'IT SENIOR'
WHEN SALARY > 50000 AND DEPARTMENT='HR' THEN 'HR SENIOR'
ELSE 'OTHERS'
END AS DEP_EMPLOYEE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, AGE, DEPARTMENT,
CASE
WHEN AGE < 18 AND DEPARTMENT = 'CSE' THEN 'YOUNG CSE'
WHEN AGE < 18 AND DEPARTMENT = 'IT' THEN 'YOUNG IT'
ELSE 'OTHERS'
END AS YOUNG_STU
FROM STUDENTS;

USE ECOMMERCEDB;
SELECT CUSTOMER_NAME, CITY, EMAIL,
CASE
WHEN CITY = CHENNAI AND EMAIL IS NOT NULL THEN 'VERIFIED CHENNAI'
WHEN CITY = CHENNAI AND EMAIL IS NULL THEN 'UNVERIFIED CHENNAI'
ELSE 'OTHER CITY'
END AS CUST_VERIFICATION
FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, BRAND,
CASE
WHEN BRAND IS NULL THEN 'UNKNOWN BRAND'
WHEN AVAILABLE_STOCK = 0 THEN 'OUT OF STOCK'
WHEN AVAILABLE_STOCK < 10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS PRODUCT_STOCK
FROM PRODUCTS;

-- CASE WITH NULL
USE STUDENTDB;
SELECT STUDENT_NAME, EMAIL,
CASE
WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
ELSE 'EMAIL MISSING'
END AS EMAIL_CHECK
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, EMAIL,
CASE
WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
ELSE 'EMAIL MISSING'
END AS EMAIL_CHECK
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, BRAND,
CASE
WHEN BRAND IS NOT NULL THEN 'BRAND AVAILABLE'
ELSE 'BRAND MISSING'
END AS BRAND_CHECK
FROM PRODUCTS;

USE LIBRARYDB;
SELECT TITLE, AUTHOR,
CASE
WHEN AUTHOR IS NOT NULL THEN 'AUTHOR AVAILABLE'
ELSE 'AUTHOR MISSING'
END AS BRAND_CHECK
FROM BOOKS;

USE ECOMMERCEDB;
SELECT CUSTOMER_NAME, EMAIL,
CASE
WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
ELSE 'EMAIL MISSING'
END AS EMAIL_CHECK
FROM  CUSTOMERS;

USE HOSPITALDB;
SELECT PATIENT_NAME, DISEASE,
CASE
WHEN DISEASE IS NOT NULL THEN 'DISEASE AVAILABLE'
ELSE 'DISEASE MISSING'
END AS DISEASE_CHECK
FROM  PATIENTS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, DISCOUNT,
CASE
WHEN DISCOUNT IS NOT NULL THEN 'DISCOUNT AVAILABLE'
ELSE 'DISCOUNT MISSING'
END AS DISCOUNT_CHECK
FROM  PRODUCTS;

USE STUDENTDB;
SELECT STUDENT_NAME, MOBILE_NUMBER,
CASE
WHEN MOBILE_NUMBER IS NOT NULL THEN 'MOBILE NUMBER AVAILABLE'
ELSE 'MOBILE NUMBER MISSING'
END AS PHONE_CHECK
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, MANAGER_NAME,
CASE
WHEN MANAGER_NAME IS NOT NULL THEN 'MANAGER ASSIGNED'
ELSE 'NO MANAGER'
END AS MANAGER_CHECK
FROM EMPLOYEES;

-- CASE WITH AGGREGATE FUNCTIONS
USE EMPLOYEEDB;
SELECT COUNT(CASE WHEN SALARY >= 50000 THEN SALARY END) AS HIGH FROM EMPLOYEES;
SELECT COUNT(CASE WHEN MARKS >= 40 THEN MARKS END) AS PASSED_STU FROM STUDENTS;
SELECT COUNT(CASE WHEN AVAILABLE_STOCK = 0 THEN 1 END) AS OUT_OF_STOCK FROM PRODUCTS;
SELECT COUNT(CASE WHEN PRICE >= 50000 THEN PRICE END) AS PRICING FROM PRODUCTS;
SELECT SUM(CASE WHEN SALARY >= 50000 THEN SALARY ELSE 0 END) AS TOTAL_EMP FROM EMPLOYEES;
SELECT SUM(CASE WHEN CATEGORY = 'ELECTRONICS' THEN PRICE ELSE 0 END) AS TOTAL_PRICE FROM PRODUCTS;
SELECT SUM(CASE WHEN AVAILABLE_STOCK > 10 THEN AVAILABLE_STOCK ELSE 0 END) AS TOTAL_STOCK FROM PRODUCTS;
SELECT COUNT(CASE WHEN ATTENDANCE >= 75 THEN ATTENDANCE ELSE 0 END) AS STU_COUNT FROM STUDENTS;
SELECT COUNT(CASE WHEN DEPARTMENT='IT' THEN 1 ELSE 0 END) AS 'IT_EMP' FROM EMPLOYEES;

-- Advanced CASE Practice
USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >= 50000 THEN 'HIGH SALARY'
WHEN SALARY < 50000 THEN 'LOW SALARY'
ELSE 'OTHERS'
END AS SALARY_GRADE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, MARKS,
CASE
WHEN MARKS >= 90 THEN 'GRADE A'
WHEN MARKS >= 75 THEN 'GRADE B'
WHEN MARKS >= 60 THEN 'GRADE C'
ELSE 'FAIL'
END AS PERFORMANCE_LEVEL
FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, PRICE, 
CASE
WHEN PRICE >= 1000 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS PRICE_CATEGORY
FROM PRODUCTS;

USE LIBRARYDB;
SELECT  TITLE, PRICE,
CASE
WHEN PRICE >= 1000 THEN 'COSTLY'
ELSE 'AFFORDABLE'
END AS PRICE_CATEGORY
FROM BOOKS;

USE ECOMMERCEDB;
SELECT CUSTOMER_NAME, AGE,
CASE
WHEN AGE >= 18 THEN 'MAJOR'
ELSE 'MINOR'
END AS AGE_CATEGORY
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 12) AS ANNUAL_SALARY,
CASE
WHEN (SALARY * 12) >= 1200000 THEN 'TAX PAYER'
ELSE 'NON_ELIGIBLE'
END AS ANNUAL_SALARY_CAT
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, 
CASE
WHEN AVAILABLE_STOCK >= 10 THEN 'AVAILABLE'
WHEN AVAILABLE_STOCK < 10 THEN 'LOW STOCK'
ELSE 'OUT OF STOCK'
END AS STOCK_STATUS
FROM PRODUCTS;

USE STUDENTDB;
SELECT STUDENT_NAME, MARKS, ATTENDANCE,
CASE
WHEN MARKS >= 90 AND ATTENDANCE >= 80 THEN 'GRADE A'
WHEN MARKS >= 75 AND ATTENDANCE <80 THEN 'GRADE B'
WHEN MARKS >= 60 AND ATTENDANCE >= 60 THEN 'GRADE C'
ELSE 'FAIL'
END AS ELIGIBILITY
FROM STUDENTS; 

USE COLLEGEDB;
SELECT COURSE_NAME, FEES,
CASE
WHEN FEES >= 80000 THEN 'HIGH FEES'
ELSE 'AFFORDABLE'
END AS FEES_CATEGORY
FROM COURSES;

USE MOVIEDB;
SELECT TITLE, RATING,
CASE
WHEN RATING >=8 THEN 'GOOD'
WHEN RATING >=5 THEN 'AVERAGE'
ELSE 'WORST'
END AS MOVIE_RATING
FROM MOVIES;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >= 90000 THEN 'A'
WHEN SALARY >= 70000 THEN 'B'
WHEN SALARY >= 50000 THEN 'C'
ELSE 'D'
END AS SALARY_GRADE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, MARKS,
CASE
WHEN MARKS >= 90 THEN 'DISTINCTION'
WHEN MARKS >= 75 THEN 'FIRST CLASS'
WHEN MARKS >= 50 THEN 'SECOND CLASS'
ELSE 'FAIL'
END AS STU_MARKS
FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, PRICE, 
CASE
WHEN PRICE >= 100000 THEN 'LUXURY'
WHEN PRICE BETWEEN 50000 AND 99999 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS PRICE_CATEGORY
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, EXPERIENCE,
CASE
WHEN EXPERIENCE >= 10 THEN 'EXPERT'
WHEN EXPERIENCE BETWEEN 5 AND 9 THEN 'EXPERIENCED'
WHEN EXPERIENCE BETWEEN 2 AND 4  THEN 'INTERMEDIATE'
WHEN EXPERIENCE BETWEEN 0 AND 2  THEN 'FRESHER'
END AS SALARY_GRADE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENT_NAME, MARKS, ATTENDANCE,
CASE
WHEN ATTENDANCE >= 90 THEN 'Excellent'
WHEN ATTENDANCE BETWEEN 75 AND 89 THEN 'GOOD'
WHEN ATTENDANCE BETWEEN 60 AND 74 THEN 'AVERAGE'
ELSE 'POOR'
END AS ELIGIBILITY
FROM STUDENTS; 

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY,
CASE
WHEN SALARY >= 90000 THEN SALARY * 0.20
WHEN SALARY >= 70000 THEN SALARY * 0.10
ELSE SALARY * 0.05
END AS SALARY_BONUS
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, PRICE, 
CASE
WHEN PRICE >= 100000 THEN PRICE * 0.20
WHEN PRICE >= 50000 THEN PRICE * 0.15
ELSE PRICE * 0.10
END AS PRICE_DISCOUNT
FROM PRODUCTS;

USE STUDENTDB;
SELECT STUDENT_NAME, MARKS,
CASE
WHEN MARKS >= 50 AND ATTENDANCE >= 75 THEN 'ELIGIBILE'
ELSE 'NOT ELIGIBILE'
END AS ELIGIBILITY
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEE_NAME, SALARY, EXPERIENCE,
CASE
WHEN EXPERIENCE >= 5 AND SALARY >= 60000 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBILE'
END AS PROMOTION
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCT_NAME, AVAILABLE_STOCK, 
CASE
WHEN AVAILABLE_STOCK = 0 THEN 'ORDER IMMEDIATELY'
WHEN AVAILABLE_STOCK < 10 THEN 'REORDER'
WHEN AVAILABLE_STOCK >= 10 THEN 'NO REORDER'
END AS REORDER_STATUS
FROM PRODUCTS;