-- UNIQUE Constraint
USE STUDENTDB;
DESC STUDENT_CONTSTAINTS;
CREATE TABLE STUDENT_CONTSTAINTS (
STUDENTID INT,
NAME VARCHAR(50),
EMAIL VARCHAR(50) UNIQUE
);

USE EMPLOYEEDB;
DESC EMPLOYEES;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES ADD COLUMN PHONE BIGINT UNIQUE;

USE SHOPPINGDB;
DESC PRODUCTS_CONSTRAINTS;
CREATE TABLE PRODUCTS_CONSTRAINTS (
PRODUCT_CODE INT UNIQUE,
PRODUCT_NAME VARCHAR(50),
PRODUCT_DESCRIPTION VARCHAR(50)
);

USE STUDENTDB;
INSERT INTO STUDENT_CONTSTAINTS VALUES (1, 'AMALA', 'AMALA@GMAIL.COM'),
(2, 'ANTONY', 'AMALA@GMAIL.COM');

-- PRIMARY KEY
USE STUDENTDB;
CREATE TABLE STUDENTS_PK (
STUDENTID INT  PRIMARY KEY,
STUDENT_ADDRESS VARCHAR(100),
STUDENT_FNAME VARCHAR(150),
STUDENT_LNAME VARCHAR(150)
);

USE EMPLOYEEDB;
CREATE TABLE EMPLOYEE_PK (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(150),
EMPLOYEE_BRANCH VARCHAR(50)
);

INSERT INTO EMPLOYEE_PK VALUES (101, 'KISHORE', 'CHENNAI'),
(101, 'JEFFY', 'TIRUNELVELI');

USE STUDENTDB;
INSERT INTO STUDENTS_PK VALUES (NULL, 'VALLIOOR', 'RAM', 'KUMAR');


-- COMPOSITE KEY
CREATE TABLE STUDENT_COURSES (
STUDENT_ID INT,
STUDENT_NAME VARCHAR(50),
COURSE_ID INT,
PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

SELECT * FROM STUDENT_COURSES;
DESC STUDENT_COURSES;
INSERT INTO STUDENT_COURSES VALUE (101, 'GHILLI', 501);
INSERT INTO STUDENT_COURSES VALUE (101, 'GHILLI', 501);
INSERT INTO STUDENT_COURSES VALUE (101, 'GHILLI', 502);

-- FOREIGN KEY
USE EMPLOYEEDB;
DESC DEPARTMENTS;
CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(100)
);

USE EMPLOYEEDB;
CREATE TABLE EMPLOYEES_FK (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

SELECT * FROM DEPARTMENTS;
INSERT INTO DEPARTMENTS VALUES (201, 'SCIENCE'),
(202, 'MATHS'), (203, 'ENGLISH'), (204, 'TAMIL');

SELECT * FROM EMPLOYEES_FK;
INSERT INTO EMPLOYEES_FK VALUES (101, 'VISHNU', 201),
(102, 'HARI', 202), (103, 'RAJESH', 201);

INSERT INTO EMPLOYEES_FK VALUES (104, 'SELVI', 210);

-- NOT NULL
USE STUDENTDB;
CREATE TABLE STUDENT_NOT_NULL (
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL
);

SELECT * FROM STUDENT_NOT_NULL;
INSERT INTO STUDENT_NOT_NULL VALUES (101, '', 'DINESH@GMAIL.COM');
INSERT INTO STUDENT_NOT_NULL VALUES (102, 'SURDISH', NULL);

-- CHECK Constraint
USE EMPLOYEEDB;
CREATE TABLE EMPLOYEE_CHECK (
EMPLOYEE_ID INT PRIMARY KEY,
SALARY INT CHECK (SALARY>10000)
);

INSERT INTO EMPLOYEE_CHECK VALUES (101, 5000);

USE STUDENTDB;
CREATE TABLE STUDENT_CHECK (
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50),
AGE TINYINT CHECK (AGE>18 AND AGE<60)
);

INSERT INTO STUDENT_CHECK VALUES (101, 'ANTO', 15);
INSERT INTO STUDENT_CHECK VALUES (101, 'ANTO', 65);

USE SHOPPINGDB;
CREATE TABLE PRODUCTS_CHECK (
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(100),
PRICE DECIMAL(10,2) CHECK (PRICE>0)
);

USE HOSPITALDB;
CREATE TABLE PATIENTS_CHECK (
PATIENT_ID INT PRIMARY KEY,
PATIENT_NAME VARCHAR(50),
AGE TINYINT CHECK (AGE>=0)
);

-- DEFAULT Constraint
USE EMPLOYEEDB;
CREATE TABLE DEPARTMENT_DEFAULT (
EMPLOYEE_ID INT PRIMARY KEY,
DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR(50) DEFAULT 'IT'
);

SELECT * FROM DEPARTMENT_DEFAULT;
INSERT INTO DEPARTMENT_DEFAULT (EMPLOYEE_ID, DEPARTMENT_ID) VALUES (202, 502);

USE SHOPPINGDB;
CREATE TABLE PRODUCTS_DEFAULT (
PRODUCT_ID INT PRIMARY KEY,
SHOP_NAME VARCHAR(100),
STOCK_QUANTITY INT DEFAULT '0');

SELECT * FROM PRODUCTS_DEFAULT;
INSERT INTO PRODUCTS_DEFAULT (PRODUCT_ID, SHOP_NAME) VALUES (1, 'MULLAI');

-- Combination Practice
USE STUDENTDB;
CREATE TABLE STUDENTS_COMBO (
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
AGE TINYINT CHECK (AGE BETWEEN 18 AND 60),
CITY VARCHAR(30) DEFAULT 'CHENNAI'
);

USE EMPLOYEEDB;
CREATE TABLE DEPARTMENT_COMBO (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE EMPLOYEES_COMBO (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(100) NOT NULL, 
EMAIL VARCHAR(100) UNIQUE,
SALARY DECIMAL(10,2) CHECK (SALARY>10000),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE STUDENTS_C (
STUDENT_ID INT,
COURSE_ID INT,
ENROLLMENT_DATE DATE,
PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

USE SHOPPINGDB;
CREATE TABLE PRODUCTS_COMBO (
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(100) NOT NULL,
STOCK_QUANTITY INT CHECK (STOCK_QUANTITY>=1),
RACK_NUMBER VARCHAR(50) UNIQUE
);