-- Student Management System
CREATE DATABASE STUDENTDB;
USE STUDENTDB;

CREATE TABLE STUDENTS (
STUDENT_ID VARCHAR(10),
STUDENT_NAME VARCHAR(50),
AGE INT,
GENDER VARCHAR(15),
EMAIL VARCHAR(50),
PHONE VARCHAR(10),
DEPARTMENT VARCHAR(20)
);

DESC STUDENTS;
SHOW TABLES;

-- Employee Management System
CREATE DATABASE EMPLOYEEDB;
USE EMPLOYEEDB;

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID VARCHAR(10),
EMPLOYEE_NAME VARCHAR(50),
DATEOFBIRTH VARCHAR(15),
GENDER VARCHAR(15),
DEPARTMENT VARCHAR(20),
JOB_ROLE VARCHAR(30),
SALARY DECIMAL(15,2),
JOINING_DATE DATE
);

DESC EMPLOYEES;
SHOW TABLES;

-- Hospital Management System
CREATE DATABASE HOSPITALDB;
USE HOSPITALDB;

CREATE TABLE PATIENTS (
PATIENT_ID INT,
PATIENT_NAME VARCHAR(50),
AGE INT,
GENDER VARCHAR(15),
BLOOD_GROUP VARCHAR(5),
PHONE VARCHAR(10),
DISEASE VARCHAR (50),
ADMISSION_DATE DATE
);

DESC PATIENTS;
SHOW TABLES;

-- Library Management System
CREATE DATABASE LIBRARYDB;
USE LIBRARYDB;

CREATE TABLE BOOKS (
BOOK_ID INT,
BOOK_NAME VARCHAR(20),
AUTHOR VARCHAR(50),
CATEGORY  VARCHAR(50),
PRICE DECIMAL(15,2),
PUBLISHED_YEAR YEAR,
QUANTITY INT
);

DESC BOOKS;
SHOW TABLES;

-- Online Shopping System
CREATE DATABASE SHOPPINGDB;
USE SHOPPINGDB;

CREATE TABLE PRODUCTS (
PRODUCT_ID VARCHAR(15),
PRODUCT_NAME VARCHAR(50),
CATEGORY  VARCHAR(50),
BRAND VARCHAR(50),
PRICE DECIMAL(15,2),
STOCK_QUANTITY INT,
MANUFACTURING_DATE DATE
);

DESC PRODUCTS;
SHOW TABLES;

-- College Management System
CREATE DATABASE COLLEGEDB;
USE COLLEGEDB;

CREATE TABLE COURSES (
COURSE_ID INT,
COURSE_NAME VARCHAR(50),
DURATION TIME,
DEPARTMENT VARCHAR(50),
FEES DECIMAL(10,2),
FACULTY_NAME VARCHAR (50)
);

DESC COURSES;
SHOW TABLES;

-- Bank Management System
CREATE DATABASE BANKDB;
USE BANKDB;

CREATE TABLE ACCOUNTS (
ACCOUNT_ID INT,
CUSTOMER_NAME VARCHAR(50),
ACCOUNT_TYPE VARCHAR(20),
ACCOUNT_NUMBER INT,
BALANCE DECIMAL(15,2),
BRANCH VARCHAR(30),
OPENING_DATE DATE
);

DESC ACCOUNTS;
SHOW TABLES;

-- Hotel Management System
CREATE DATABASE HOTELDB;
USE HOTELDB;

CREATE TABLE ROOMS (
ROOM_ID INT,
ROOM_NUMBER INT,
ROOM_TYPE VARCHAR(20),
PRICE_PERDAY DECIMAL(15,2),
AVAILABILITY CHAR(1),
FLOOR_NUMBER INT
);

DESC ROOMS;
SHOW TABLES;

-- Movie Ticket Booking System
CREATE DATABASE MOVIEDB;
USE MOVIEDB;

CREATE TABLE MOVIES (
MOVIE_ID INT,
MOVIE_NAME VARCHAR(50),
GENRE VARCHAR(20),
LANGUAGE VARCHAR(30),
DURATION TIME,
RELEASE_DATE DATE,
RATING INT
);

DESC MOVIES;
SHOW TABLES;

-- E-Commerce Customer System
CREATE DATABASE ECOMMERCEDB;
USE ECOMMERCEDB;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PHONE VARCHAR(10),
CITY VARCHAR(20),
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
REGISTRATION_DATE DATE
);

DESC CUSTOMERS;
SHOW TABLES;

select * from CUSTOMERS;