USE STUDENTDB;
SELECT DISTINCT DEPARTMENT FROM STUDENTS;
SELECT DISTINCT GENDER FROM STUDENTS;

USE EMPLOYEEDB;
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES;
SELECT DISTINCT DESIGNATION FROM EMPLOYEES;

USE HOSPITALDB;
SELECT DISTINCT BLOOD_GROUP FROM PATIENTS;
SELECT DISTINCT DISEASE FROM PATIENTS;

USE LIBRARYDB;
SELECT DISTINCT CATEGORY FROM BOOKS;
SELECT DISTINCT AUTHOR FROM BOOKS;

USE SHOPPINGDB;
SELECT DISTINCT CATEGORY FROM PRODUCTS;
SELECT DISTINCT BRAND FROM PRODUCTS;

USE COLLEGEDB;
SELECT DISTINCT DEPARTMENT FROM COURSES;
SELECT DISTINCT DURATION FROM COURSES;

USE MOVIEDB;
SELECT DISTINCT LANGUAGE FROM MOVIES;
SELECT DISTINCT GENRE FROM MOVIES;

USE ECOMMERCEDB;
SELECT DISTINCT CITY FROM CUSTOMERS;
SELECT DISTINCT STATE FROM CUSTOMERS;
SELECT DISTINCT COUNTRY FROM CUSTOMERS;
SELECT DISTINCT CITY, STATE FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT DISTINCT DEPARTMENT, DESIGNATION FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT DISTINCT CATEGORY, BRAND FROM PRODUCTS;

-- DISTINCT with Conditions
USE STUDENTDB;
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE AGE>20;

USE EMPLOYEEDB;
SELECT DISTINCT DESIGNATION FROM EMPLOYEES WHERE SALARY>40000;

USE HOSPITALDB;
SELECT DISTINCT DISEASE FROM PATIENTS WHERE AGE>30;

USE LIBRARYDB;
SELECT DISTINCT CATEGORY FROM BOOKS WHERE PRICE>500;

USE SHOPPINGDB;
SELECT DISTINCT BRAND FROM PRODUCTS WHERE PRICE>10000;

USE MOVIEDB;
SELECT DISTINCT GENRE FROM MOVIES WHERE RATING>4;

USE ECOMMERCEDB;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE COUNTRY='INDIA';

USE STUDENTDB;
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE DEPARTMENT='IT' OR DEPARTMENT='CSE';

USE EMPLOYEEDB;
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE SALARY BETWEEN 30000 AND 60000;

USE SHOPPINGDB;
SELECT DISTINCT CATEGORY FROM PRODUCTS WHERE AVAILABLE_STOCK>10;

-- DISTINCT with Other Operators
USE STUDENTDB;
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE DEPARTMENT IN ('IT','CSE','ECE');

USE EMPLOYEEDB;
SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE DEPARTMENT NOT IN ('HR', 'FINANCE');

USE SHOPPINGDB;
SELECT DISTINCT CATEGORY FROM PRODUCTS WHERE PRICE BETWEEN 5000 AND 50000;

USE LIBRARYDB;
SELECT DISTINCT CATEGORY FROM BOOKS WHERE PRICE NOT BETWEEN 500 AND 1000;

USE ECOMMERCEDB;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE EMAIL IS NOT NULL;
SELECT DISTINCT CITY FROM CUSTOMERS WHERE EMAIL IS NULL;

SELECT DISTINCT DEPARTMENT FROM EMPLOYEES WHERE SALARY>50000;
SELECT DISTINCT DEPARTMENT FROM STUDENTS WHERE AGE NOT BETWEEN 18 AND 25;
SELECT DISTINCT BRAND FROM PRODUCTS WHERE BRAND IS NOT NULL;
SELECT DISTINCT BLOOD_GROUP FROM PATIENTS WHERE DISEASE IS NULL;



