USE STUDENTDB;
USE EMPLOYEEDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE ECOMMERCEDB;
USE HOSPITALDB;
USE COLLEGEDB;

-- Arithmetic Expressions
SELECT EMPLOYEE_NAME, SALARY, (SALARY + 5000) AS SALARY_BONUS FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 0.10) AS SALARY_INCREMENT FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, SALARY, (SALARY - 2000) AS SALARY_DEDUCTION FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 12) AS SALARY_BONUS FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 0.95) AS DEDUCTION FROM EMPLOYEES;
SELECT PRODUCT_NAME, PRICE, (PRICE * 0.18) AS PRICE_GST FROM PRODUCTS;
SELECT PRODUCT_NAME, PRICE, (PRICE * 0.85) AS DISCOUNTED_PRICE FROM PRODUCTS;
SELECT TITLE, PRICE, (PRICE * 0.10) AS PRICE_TAX FROM BOOKS;
SELECT TITLE, PRICE, (PRICE * 0.80) AS PRICE_DISCOUNT FROM BOOKS;
SELECT COURSE_NAME, FEES, (FEES * 0.05) AS FEES_GST FROM COURSES;
SELECT COURSE_NAME, FEES, (FEES * 0.90) AS FEES_DISCOUNT FROM COURSES;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, (PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS;
SELECT TITLE, PRICE, (PRICE * QUANTITY) AS TOTAL_VALUE FROM BOOKS;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 0.10) * 12 AS SALARY_INCREMENT FROM EMPLOYEES;
SELECT PRODUCT_NAME, PRICE, (PRICE * 0.80) * 1.18 AS PRICE_GST FROM PRODUCTS;
SELECT EMPLOYEE_NAME, SALARY, (SALARY + 3000) AS ALLOWANCE FROM EMPLOYEES;
SELECT COURSE_NAME, FEES, (FEES * 0.85) AS SCHOLARSHIP FROM COURSES;
SELECT EMPLOYEE_NAME, SALARY, (SALARY - 50000) AS DIFFERENCE FROM EMPLOYEES;

-- Comparison Expressions
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > 50000;
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY < 30000;
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > 20;
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE = 20;
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE = 10000;
SELECT PRODUCT_NAME FROM PRODUCTS WHERE AVAILABLE_STOCK < 10; 
SELECT TITLE FROM BOOKS WHERE PRICE BETWEEN 500 AND 1000;
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY <> 40000;
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE >= 18;
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE <= 50000;
SELECT COURSE_NAME FROM COURSES WHERE FEES >= 30000;
SELECT TITLE FROM MOVIES WHERE RATING >= 4;
SELECT PATIENT_NAME FROM PATIENTS WHERE AGE < 60;
SELECT CUSTOMER_NAME FROM CUSTOMERS WHERE AGE <> 25;
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY BETWEEN 40000 AND 70000;

-- Logical Expressions
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > 40000 AND DEPARTMENT='IT';
SELECT STUDENT_NAME FROM STUDENTS WHERE AGE > 20 AND DEPARTMENT='CSE';
SELECT PRODUCT_NAME FROM PRODUCTS WHERE PRICE > 10000 AND AVAILABLE_STOCK >10;
SELECT TITLE FROM BOOKS WHERE PRICE > 500 AND CATEGORY='TECHNOLOGY';
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE DEPARTMENT='IT' OR DEPARTMENT='HR';
SELECT STUDENT_NAME, DEPARTMENT FROM STUDENTS WHERE DEPARTMENT NOT LIKE 'IT';
SELECT PRODUCT_NAME FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' AND PRICE BETWEEN 10000 AND 50000;
SELECT CUSTOMER_NAME FROM CUSTOMERS WHERE CITY='CHENNAI' OR CITY='BANGALORE';
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY > 50000 AND DESIGNATION='DEVELOPER';
SELECT TITLE FROM BOOKS WHERE PRICE < 500 OR PRICE > 1500;
SELECT PATIENT_NAME FROM PATIENTS WHERE AGE < 30 AND BLOOD_GROUP='O+';
SELECT STUDENT_NAME FROM STUDENTS WHERE DEPARTMENT='IT' OR AGE > 22;
SELECT PRODUCT_NAME FROM PRODUCTS WHERE BRAND IS NOT NULL AND PRICE > 5000;
SELECT CUSTOMER_NAME FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY='CHENNAI';
SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE SALARY NOT BETWEEN 30000 AND 60000;

-- String Expressions
SELECT UPPER(STUDENT_NAME) AS UPPERCASE FROM STUDENTS;
SELECT LOWER(EMPLOYEE_NAME) AS LOWERCASE FROM EMPLOYEES;
SELECT STUDENT_NAME, LENGTH(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT LEFT(EMPLOYEE_NAME, 3) AS LEFT_NAME FROM EMPLOYEES;
SELECT RIGHT(STUDENT_NAME, 2) AS RIGHT_NAME FROM STUDENTS;
SELECT UPPER(PRODUCT_NAME), PRICE AS UPPERCASE FROM PRODUCTS;
SELECT LENGTH(CUSTOMER_NAME) AS NAME_LENGTH FROM CUSTOMERS;
SELECT TRIM(TITLE) AS BOOK_NAMETRIM FROM BOOKS;
SELECT CONCAT(STUDENT_NAME, DEPARTMENT) AS NAME_CONCAT FROM STUDENTS;
SELECT CONCAT(PRODUCT_NAME, 'BY', BRAND) AS PRO_DET FROM PRODUCTS;
SELECT CONCAT(CITY, STATE) AS ADDRESS_DET FROM CUSTOMERS;
SELECT CONCAT(COURSE_NAME, DEPARTMENT) AS NAME_CONCAT FROM COURSES;
SELECT LEFT(STUDENT_NAME,1) FROM STUDENTS;
SELECT RIGHT(EMPLOYEE_NAME, 1) FROM EMPLOYEES;

--  Date & Time Expressions
SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();
SELECT NOW();
SELECT EMPLOYEE_NAME, JOINING_DATE, DATE_ADD(CURRENT_DATE(), INTERVAL 30 DAY) FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, JOINING_DATE, DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY) FROM EMPLOYEES;
SELECT PATIENT_NAME, ADMISSION_DATE, DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY) FROM PATIENTS;
SELECT CUSTOMER_NAME, REGISTERED_DATE, DATE_SUB(CURRENT_DATE(), INTERVAL 42 DAY) FROM CUSTOMERS;
SELECT PRODUCT_NAME, MANUFACTURING_DATE, DATE_ADD(CURRENT_DATE(), INTERVAL 126 DAY) FROM PRODUCTS;
SELECT EMPLOYEE_NAME, JOINING_DATE, DATE_FORMAT(CURRENT_DATE(), '%d-%m-%Y') FROM EMPLOYEES;
SELECT CUSTOMER_NAME, REGISTERED_DATE, DATE_FORMAT(CURRENT_DATE(), '%m/%d/%Y') FROM CUSTOMERS;
SELECT MANUFACTURING_DATE, DATE_FORMAT(CURRENT_DATE(), '%d-%M-%Y') FROM PRODUCTS;
SELECT YEAR(JOINING_DATE) FROM EMPLOYEES;
SELECT MONTH(REGISTERED_DATE) FROM CUSTOMERS;
SELECT DATE(MANUFACTURING_DATE) FROM PRODUCTS;

-- Aggregate Expressions
SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT COUNT(*) AS TOTAL_EMP FROM EMPLOYEES;
SELECT SUM(PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS;
SELECT AVG(PRICE) FROM PRODUCTS;
SELECT MAX(PRICE) FROM BOOKS;
SELECT MIN(FEES) FROM COURSES;
SELECT COUNT(*) FROM PRODUCTS WHERE PRICE > 10;

-- Expression with Alias
SELECT SALARY AS MONTHLY_SALARY FROM EMPLOYEES;
SELECT SALARY, (SALARY * 12) AS ANNUAL_SALARY FROM EMPLOYEES;
SELECT PRICE, (PRICE * DISCOUNT) AS DISCOUNTED_PRICE FROM PRODUCTS;
SELECT PRICE, (PRICE * GST) AS FINAL_PRICE FROM PRODUCTS;
SELECT PRICE, (PRICE * AVAILABLE_STOCK) AS STOCK_VALUE FROM PRODUCTS;
SELECT PRICE, (PRICE * 0.90) AS DISCOUNTED_PRICE FROM BOOKS;
SELECT FEES, (FEES * 0.85) AS DISCOUNTED_FEES FROM COURSES;
SELECT LENGTH(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS;
SELECT SALARY, (SALARY * 0.10) AS INCREMENTED_SALARY FROM EMPLOYEES;
SELECT PRICE, (PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS;