-- IN Operator
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE DEPARTMENT IN ('IT', 'CSE', 'ECE');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT', 'HR', 'FINANCE');

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP IN ('A+', 'B+', 'O+');

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE CATEGORY IN ('TECHNOLOGY', 'HISTORY', 'SCIENCE');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('ELECTRONICS', 'ACCESSORIES', 'FURNITURE');

USE COLLEGEDB;
SELECT * FROM COURSES WHERE DEPARTMENT IN ('CSE', 'IT', 'ECE');

USE MOVIEDB;
SELECT * FROM MOVIES WHERE LANGUAGE IN ('TAMIL', 'ENGLISH', 'HINDI');

USE HOTELDB;
SELECT * FROM ROOMS WHERE ROOM_TYPE IN ('SINGLE', 'DOUBLE', 'DELUXE');

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CITY IN ('CHENNAI', 'COIMBATORE', 'MADURAI');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE DESIGNATION IN ('DEVELOPER', 'TESTER', 'ANALYST');

-- NOT IN Operator
SELECT * FROM STUDENTS WHERE DEPARTMENT NOT IN ('IT', 'CSE', 'ECE');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT NOT IN ('HR', 'FINANCE');
SELECT * FROM PATIENTS WHERE BLOOD_GROUP NOT IN ('A+', 'B+', 'O+');
SELECT * FROM BOOKS WHERE CATEGORY NOT IN ('TECHNOLOGY', 'HISTORY');
SELECT * FROM PRODUCTS WHERE CATEGORY NOT IN ('ELECTRONICS', 'ACCESSORIES');
SELECT * FROM COURSES WHERE DEPARTMENT NOT IN ('CSE', 'IT');
SELECT * FROM MOVIES WHERE LANGUAGE NOT IN ('TAMIL', 'ENGLISH');
SELECT * FROM ROOMS WHERE ROOM_TYPE NOT IN ('SINGLE', 'DOUBLE');
SELECT * FROM CUSTOMERS WHERE CITY NOT IN ('CHENNAI', 'COIMBATORE');
SELECT * FROM EMPLOYEES WHERE DESIGNATION NOT IN ('DEVELOPER', 'TESTER', 'ANALYST');

-- IN with Numeric Values
SELECT * FROM STUDENTS WHERE STUDENT_ID IN (101, 105, 110);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (201, 205, 210);
SELECT * FROM PRODUCTS WHERE PRODUCT_ID IN (501, 505, 510);
SELECT * FROM BOOKS WHERE PRICE IN (500, 750, 1000);
SELECT * FROM ROOMS WHERE ROOM_NUMBER IN (101, 205, 301);

-- NOT IN with Numeric Values
SELECT * FROM STUDENTS WHERE STUDENT_ID NOT IN (101, 105, 110);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID NOT IN (201, 205, 210);
SELECT * FROM PRODUCTS WHERE PRODUCT_ID NOT IN (501, 505, 510);
SELECT * FROM BOOKS WHERE PRICE NOT IN (500, 750, 1000);
SELECT * FROM ROOMS WHERE ROOM_NUMBER NOT IN (101, 205, 301);

-- IN / NOT IN with Conditions
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN ('IT', 'HR', 'FINANCE') AND SALARY>40000;
SELECT * FROM STUDENTS WHERE DEPARTMENT IN ('CSE', 'IT', 'ECE') AND AGE>20;
SELECT * FROM PRODUCTS WHERE CATEGORY IN ('ELECTRONICS', 'ACCESSORIES') AND PRICE>5000;
SELECT * FROM BOOKS WHERE CATEGORY IN ('TECHNOLOGY', 'SCIENCE') AND PRICE>1000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT NOT IN ('HR', 'FINANCE') AND SALARY>30000;
SELECT * FROM STUDENTS WHERE DEPARTMENT NOT IN ('CSE', 'IT') AND ADE>21;
SELECT * FROM PRODUCTS WHERE CATEGORY NOT IN ('ELECTRONICS', 'FURNITURE') AND AVAILABLE_STOCK>10;
SELECT * FROM MOVIES WHERE LANGUAGE IN ('TAMIL', 'ENGLISH', 'HINDI') AND RATING>4;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP NOT IN ('A+', 'B+', 'O+') AND AGE>30;