USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE MOVIEDB;
USE HOTELDB;
USE ECOMMERCEDB;

-- IS NULL 
SELECT * FROM STUDENTS WHERE EMAIL IS NULL;
SELECT * FROM STUDENTS WHERE MOBILE_NUMBER IS NULL;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NULL;
SELECT * FROM EMPLOYEES WHERE EMAIL IS NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL;
SELECT * FROM PATIENTS WHERE DOCTOR_NAME IS NULL;
SELECT * FROM BOOKS WHERE PUBLISHED_YEAR IS NULL;
SELECT * FROM BOOKS WHERE AUTHOR IS NULL;
SELECT * FROM PRODUCTS WHERE BRAND IS NULL;
SELECT * FROM PRODUCTS WHERE MANUFACTURING_DATE IS NULL;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL;
SELECT * FROM CUSTOMERS WHERE COUNTRY IS NULL;

-- IS NOT NULL
SELECT * FROM STUDENTS WHERE EMAIL IS NOT NULL;
SELECT * FROM STUDENTS WHERE DEPARTMENT IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE SALARY IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE EMAIL IS NOT NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NOT NULL;
SELECT * FROM PATIENTS WHERE DOCTOR_NAME IS NOT NULL;
SELECT * FROM BOOKS WHERE PRICE IS NOT NULL;
SELECT * FROM BOOKS WHERE AUTHOR IS NOT NULL;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL;
SELECT * FROM PRODUCTS WHERE MANUFACTURING_DATE IS NOT NULL;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL;
SELECT * FROM CUSTOMERS WHERE COUNTRY IS NOT NULL;

-- IS NULL with Conditions
SELECT * FROM STUDENTS WHERE EMAIL IS NULL AND DEPARTMENT='IT';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NULL AND SALARY>30000;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL AND AGE>25;
SELECT * FROM PRODUCTS WHERE BRAND IS NULL AND PRICE>5000;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL AND CITY='CHENNAI';

-- IS NOT NULL with Conditions
SELECT * FROM STUDENTS WHERE EMAIL IS NOT NULL AND DEPARTMENT='CSE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IS NOT NULL AND SALARY>40000;
SELECT * FROM PATIENTS WHERE DISEASE IS NOT NULL AND AGE>30;
SELECT * FROM BOOKS WHERE AUTHOR IS NOT NULL AND PRICE>1000;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL AND AVAILABLE_STOCK>5000;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY='CHENNAI';

-- Mixed Practice
SELECT * FROM STUDENTS WHERE EMAIL IS NULL OR DEPARTMENT='IT';
SELECT * FROM EMPLOYEES WHERE EMAIL IS NOT NULL AND DEPARTMENT IN ('IT', 'HR');
SELECT * FROM PRODUCTS WHERE BRAND IS NULL OR DISCOUNT IS NULL;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND COUNTRY IS NOT NULL;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL AND PHONE IS NOT NULL;