-- LIKE with %
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A%';
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE '%A';
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE '%A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'R%';
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'N%';
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE '%AR%';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE 'P%';
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE '%I';
SELECT * FROM PATIENTS WHERE DISEASE LIKE '%FEVER%';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE 'S%';
SELECT * FROM BOOKS WHERE TITLE LIKE '%SQL';
SELECT * FROM BOOKS WHERE TITLE LIKE '%DATA%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'M%';
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%PHONE';
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%BOOK%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE 'K%';
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE '%A';
SELECT * FROM CUSTOMERS WHERE CITY LIKE '%PUR%';

USE COLLEGEDB;
SELECT * FROM COURSES WHERE COURSE_NAME LIKE '%DATA%';

USE MOVIEDB;
SELECT * FROM MOVIES WHERE TITLE LIKE 'THE%';

-- LIKE with _
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A____';
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'L_____';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'L____';
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'A_____';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE 'D___';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE 'E___';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'T______';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE 'W____';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE '_A____';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE '_R____';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE '__I__';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE BOOK_NAME LIKE '_O____';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '_A_____'; 

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE '_A___';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'AK____';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'R_H___';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE 'S_L___';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'M__I__';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE 'K___A';

USE MOVIEDB;
SELECT * FROM MOVIES WHERE TITLE LIKE '_______';

-- Combining % and _
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A_%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'R_H%';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE 'P%A';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE 'S_%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'M%E';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE 'K%A';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE '_A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE '_R%N';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE 'D_SQL%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'PHONE%R';

-- NOT LIKE –
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME NOT LIKE 'A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME NOT LIKE '%N';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE DISEASE NOT LIKE '%FEVER%';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE NOT LIKE 'S%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME NOT LIKE '%PHONE%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME NOT LIKE '%A';

USE COLLEGEDB;
SELECT * FROM COURSES WHERE COURSE_NAME NOT LIKE '%DATA%';

USE MOVIEDB;
SELECT * FROM MOVIES WHERE TITLE NOT LIKE 'THE%';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME NOT LIKE '%AN%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME NOT LIKE 'R%';

-- LIKE with Other Conditions
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A%' AND AGE>20;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE 'R%' AND SALARY>40000;

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE 'P%' AND AGE BETWEEN 20 AND 40;

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE '%SQL%' AND PRICE<1000;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%PHONE%' AND PRICE>5000;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_NAME LIKE 'K%' AND CITY='CHENNAI';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' AND STUDENT_NAME LIKE 'A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' AND EMPLOYEE_NAME LIKE '%AR%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' AND BRAND LIKE 'S%';

USE MOVIEDB;
SELECT * FROM MOVIES WHERE LANGUAGE='TAMIL' AND TITLE LIKE 'M%';

-- Mixed LIKE & Wildcard Challenge
USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A%A';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'S_R%';

USE HOSPITALDB;
SELECT * FROM PATIENTS WHERE PATIENT_NAME LIKE '%RI%';

USE LIBRARYDB;
SELECT * FROM BOOKS WHERE TITLE LIKE '%DATA%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'SMART%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS WHERE CITY LIKE '%PUR';

USE COLLEGEDB;
SELECT * FROM COURSES WHERE COURSE_NAME LIKE 'DATA%SCIENCE%';

USE MOVIEDB;
SELECT * FROM MOVIES WHERE TITLE LIKE '%LOVE%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE 'A_____';

USE STUDENTDB;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE '____A';