USE STUDENTDB;
USE EMPLOYEEDB;
USE SHOPPINGDB;

SELECT EMPLOYEE_NAME FROM EMPLOYEES LIMIT 5;	
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 10;
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY LIMIT 5;
SELECT PRODUCT_NAME, PRICE FROM PRODUCTS ORDER BY PRICE DESC LIMIT 5;
SELECT EMPLOYEE_NAME FROM EMPLOYEES LIMIT 5 OFFSET 3;
SELECT STUDENT_NAME FROM STUDENTS LIMIT 10 OFFSET 10;
SELECT PRODUCT_NAME FROM PRODUCTS LIMIT 10 OFFSET 10;
SELECT EMPLOYEE_NAME FROM EMPLOYEES LIMIT 5 OFFSET 10;
SELECT PRODUCT_NAME, PRICE FROM PRODUCTS ORDER BY PRICE DESC LIMIT 3 OFFSET 1;
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 5 OFFSET 5;