USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE MOVIEDB;
USE HOTELDB;
USE ECOMMERCEDB;

-- AND Operator
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' AND AGE>20;
SELECT * FROM STUDENTS WHERE AGE BETWEEN 18 AND 25 AND GENDER='FEMALE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' AND SALARY>40000;
SELECT * FROM EMPLOYEES WHERE SALARY>50000 AND DESIGNATION='DEVELOPER';
SELECT * FROM PATIENTS WHERE AGE>30 AND GENDER='FEMALE';
SELECT * FROM PATIENTS WHERE BLOOD_GROUP='O+' AND DISEASE='FEVER';
SELECT * FROM BOOKS WHERE CATEGORY='TECHNOLOGY' AND PRICE>500;
SELECT * FROM BOOKS WHERE PRICE BETWEEN 500 AND 1000 AND CATEGORY='TECHNOLOGY';
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' AND PRICE>10000;
SELECT * FROM PRODUCTS WHERE AVAILABLE_STOCK>10 AND PRICE>50000;
SELECT * FROM COURSES WHERE DEPARTMENT='CSE' AND FEES>30000;
SELECT * FROM COURSES WHERE DURATION>6 AND FEES<50000;
SELECT * FROM MOVIES WHERE LANGUAGE='TAMIL' AND RATING>4;
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI' AND COUNTRY='INDIA';
SELECT * FROM STUDENTS WHERE DEPARTMENT='CSE' AND AGE BETWEEN 18 AND 25;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' AND SALARY BETWEEN 40000 AND 70000;
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' AND BRAND='SAMSUNG';
SELECT * FROM BOOKS WHERE AUTHOR='JOHN' AND PRICE>500;
SELECT * FROM PATIENTS WHERE DISEASE IS NULL AND AGE>25;
SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY='CHENNAI';

-- OR Operator
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' OR DEPARTMENT='CSE';
SELECT * FROM STUDENTS WHERE AGE<10 OR AGE>25;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' OR DEPARTMENT='HR';
SELECT * FROM EMPLOYEES WHERE SALARY>60000 OR SALARY<30000;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP='A+' OR BLOOD_GROUP='O+';
SELECT * FROM PATIENTS WHERE DISEASE='FEVER' OR DISEASE='COLD';
SELECT * FROM BOOKS WHERE CATEGORY='TECHNOLOGY' OR CATEGORY='SCIENCE';
SELECT * FROM BOOKS WHERE PRICE<500 OR PRICE>1500;
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' OR CATEGORY='ACCESSORIES';
SELECT * FROM PRODUCTS WHERE PRICE>50000 AND AVAILABLE_STOCK<5;
SELECT * FROM COURSES WHERE COURSE_NAME='CSE' OR COURSE_NAME='IT';
SELECT * FROM COURSES WHERE FEES<25000 OR FEES>75000;
SELECT * FROM MOVIES WHERE LANGUAGE='TAMIL' OR LANGUAGE='ENGLISH';
SELECT * FROM MOVIES WHERE RATING>4.5 OR RATING<3;
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI' OR CITY='BANGALORE';
SELECT * FROM STUDENTS WHERE DEPARTMENT='CSE' OR AGE>22;
SELECT * FROM EMPLOYEES WHERE DESIGNATION='DEVELOPER' OR DESIGNATION='TESTER';
SELECT * FROM PRODUCTS WHERE BRAND='SAMSUNG' OR BRAND='APPLE';
SELECT * FROM BOOKS WHERE CATEGORY='TECHNOLOGY' OR PRICE>1000;
SELECT * FROM PATIENTS WHERE AGE>50 OR BLOOD_GROUP='O-';

-- NOT Operator
SELECT * FROM STUDENTS WHERE NOT DEPARTMENT='IT';
SELECT * FROM STUDENTS WHERE NOT AGE>20;
SELECT * FROM EMPLOYEES WHERE NOT DEPARTMENT='HR';
SELECT * FROM EMPLOYEES WHERE NOT DESIGNATION='DEVELOPER';
SELECT * FROM PATIENTS WHERE NOT GENDER='MALE';
SELECT * FROM PATIENTS WHERE NOT BLOOD_GROUP='O+';
SELECT * FROM BOOKS WHERE NOT CATEGORY='TECHNOLOGY';
SELECT * FROM BOOKS WHERE NOT PRICE BETWEEN 500 AND 1000;
SELECT * FROM PRODUCTS WHERE NOT CATEGORY='ELECTRONICS';
SELECT * FROM PRODUCTS WHERE NOT PRICE>10000;
SELECT * FROM COURSES WHERE NOT DEPARTMENT='CSE';
SELECT * FROM COURSES WHERE NOT FEES BETWEEN 30000 AND 60000;
SELECT * FROM MOVIES WHERE NOT LANGUAGE='TAMIL';
SELECT * FROM MOVIES WHERE NOT RATING>4;
SELECT * FROM CUSTOMERS WHERE NOT CITY='CHENNAI';
SELECT * FROM STUDENTS WHERE NOT DEPARTMENT='CSE' AND AGE>20;
SELECT * FROM EMPLOYEES WHERE NOT DEPARTMENT='IT' AND SALARY>30000;
SELECT * FROM PRODUCTS WHERE NOT CATEGORY='ELECTRONICS' AND AVAILABLE_STOCK>10;
SELECT * FROM BOOKS WHERE NOT CATEGORY='TECHNOLOGY' AND PRICE>1000;
SELECT * FROM PATIENTS WHERE NOT DISEASE='FEVER';

-- Mixed Logical Operator 
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' AND AGE >20 OR DEPARTMENT='CSE';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' AND SALARY>50000 OR DESIGNATION='MANAGER';
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' AND PRICE>10000 OR BRAND='APPLE';
SELECT * FROM BOOKS WHERE CATEGORY='TECHNOLOGY' AND PRICE>500 OR AUTHOR='JOHN';
SELECT * FROM PATIENTS WHERE GENDER='FEMALE' AND AGE>30 OR BLOOD_GROUP='O+';
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI' AND EMAIL IS NOT NULL OR CITY='BANGALORE';
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' OR DEPARTMENT='CSE' AND AGE>20;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' OR DEPARTMENT='HR' AND SALARY>40000;
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' OR CATEGORY='ACCESSORIES' AND PRICE BETWEEN 5000 AND 50000;
SELECT * FROM MOVIES WHERE LANGUAGE='TAMIL' OR LANGUAGE='ENGLISH' AND RATING>4;

-- Logical Operators with NULL, IN, BETWEEN, and LIKE
SELECT * FROM STUDENTS WHERE DEPARTMENT='IT' AND EMAIL IS NOT NULL;
SELECT * FROM EMPLOYEEES WHERE DEPARTMENT='IT' AND EMAIL IS NULL;
SELECT * FROM PATIENTS WHERE BLOOD_GROUP='A+' OR BLOOD_GROUP='B+' AND AGE>25;
SELECT * FROM BOOKS WHERE CATEGORY IN ('TECHNOLOGY', 'SCIENCE') AND PRICE BETWEEN 500 AND 1500;
SELECT * FROM PRODUCTS WHERE BRAND IS NOT NULL AND PRICE>10000;
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI' OR CITY='COIMBATORE' AND EMAIL IS NOT NULL;
SELECT * FROM STUDENTS WHERE STUDENT_NAME LIKE 'A%' AND AGE>20;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_NAME LIKE '%AN%' OR SALARY>50000;
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%PHONE%' AND PRICE BETWEEN 5000 AND 50000;
SELECT * FROM BOOKS WHERE BOOK_NAME LIKE 'S%' OR CATEGORY='TECHNOLOGY';