USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE MOVIEDB;
USE ECOMMERCEDB;

SELECT EMPLOYEE_NAME, ROUND(SALARY, -3) AS ROUNDED_SALARY FROM EMPLOYEES;
SELECT SALARY, ABS(SALARY - 50000) AS DIFFERENCE FROM EMPLOYEES;
SELECT PRICE, CEIL(PRICE) AS CEILING_VALUE FROM PRODUCTS;
SELECT PRICE, FLOOR(PRICE) AS CEILING_VALUE FROM PRODUCTS;
SELECT EMPLOYEE_NAME, SALARY, MOD(SALARY, 10000) AS REMINDER FROM EMPLOYEES;
SELECT STUDENT_NAME, MARKS, POWER(MARKS, 2) AS SQUARE_STUDENT_MARKS FROM STUDENTS;
SELECT PRODUCT_NAME, PRICE, SQRT(PRICE) AS SQUARE_ROOT FROM PRODUCTS;
SELECT PRODUCT_NAME, PRICE, ROUND(PRICE, 2) AS ROUNDED_PRICE FROM PRODUCTS;
