USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE MOVIEDB;
USE HOTELDB;
USE ECOMMERCEDB;

SELECT * FROM STUDENTS ORDER BY STUDENT_NAME;
SELECT * FROM STUDENTS ORDER BY STUDENT_NAME DESC;
SELECT * FROM EMPLOYEES ORDER BY SALARY;
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM PRODUCTS ORDER BY PRICE;
SELECT * FROM PRODUCTS ORDER BY PRICE DESC;
SELECT * FROM BOOKS ORDER BY PRICE;
SELECT * FROM BOOKS ORDER BY PRICE DESC;
SELECT * FROM STUDENTS ORDER BY AGE;
SELECT * FROM STUDENTS ORDER BY AGE DESC;
SELECT * FROM EMPLOYEES ORDER BY JOINING_DATE;
SELECT * FROM EMPLOYEES ORDER BY JOINING_DATE DESC;
SELECT * FROM COURSES ORDER BY FEES;
SELECT * FROM COURSES ORDER BY FEES DESC;
SELECT * FROM MOVIES ORDER BY RATING DESC;
SELECT * FROM CUSTOMERS ORDER BY CITY;
SELECT * FROM PRODUCTS ORDER BY AVAILABLE_STOCK DESC;
SELECT * FROM PATIENTS ORDER BY AGE;
SELECT * FROM EMPLOYEES ORDER BY EXPERIENCE DESC;
SELECT * FROM BOOKS ORDER BY PUBLISHED_DATE;

--  ORDER BY with WHERE
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' ORDER BY SALARY;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT='IT' ORDER BY SALARY DESC;
SELECT * FROM STUDENTS WHERE DEPARTMENT='CSE' ORDER BY AGE DESC;
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' ORDER BY PRICE;
SELECT * FROM BOOKS WHERE PRICE>500 ORDER BY PRICE DESC;
SELECT * FROM EMPLOYEES WHERE SALARY>40000 ORDER BY SALARY DESC;
SELECT * FROM STUDENTS WHERE AGE>20 ORDER BY STUDENT_NAME;
SELECT * FROM PRODUCTS WHERE AVAILABLE_STOCK<10 ORDER BY AVAILABLE_STOCK;
SELECT * FROM COURSES WHERE FEES>30000 ORDER BY FEES;
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI' ORDER BY CUSTOMER_NAME;

-- ORDER BY with Multiple Columns
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT ASC, SALARY DESC;
SELECT * FROM STUDENTS ORDER BY DEPARTMENT ASC, AGE DESC;
SELECT * FROM PRODUCTS ORDER BY CATEGORY ASC, PRICE DESC;
SELECT * FROM BOOKS ORDER BY CATEGORY, PRICE;
SELECT * FROM EMPLOYEES ORDER BY DESIGNATION ASC, SALARY DESC;
SELECT * FROM STUDENTS ORDER BY DESIGNATION ASC, SALARY DESC;
SELECT * FROM CUSTOMERS ORDER BY CITY, CUSTOMER_NAME;
SELECT * FROM PRODUCTS ORDER BY BRAND ASC, PRICE DESC;
SELECT * FROM COURSES ORDER BY DEPARTMENT ASC, FEES DESC;
SELECT * FROM PATIENTS ORDER BY BLOOD_GROUP ASC, AGE DESC;

-- ORDER BY with Expressions
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, (PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS ORDER BY TOTAL_VALUE DESC;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 1.10) AS INCREMENTED_SALARY FROM EMPLOYEES ORDER BY INCREMENTED_SALARY;
SELECT PRODUCT_NAME, PRICE, (PRICE * 0.90) AS DISCOUNTED_PRICE FROM PRODUCTS ORDER BY DISCOUNTED_PRICE;
SELECT STUDENT_NAME, LENGTH(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS ORDER BY NAME_LENGTH DESC;
SELECT EMPLOYEE_NAME FROM EMPLOYEES ORDER BY SALARY;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, (PRICE * AVAILABLE_STOCK) AS STOCK_VALUE FROM PRODUCTS ORDER BY STOCK_VALUE DESC;
SELECT BOOK_NAME, PRICE, (PRICE * 0.80) AS DISCOUNTED_PRICE FROM BOOKS ORDER BY DISCOUNTED_PRICE;
SELECT COURSE_NAME, FEES, (FEES * 0.85) AS DISCOUNTED_FEES FROM COURSES ORDER BY DISCOUNTED_FEES;
SELECT STUDENT_NAME, AGE, (AGE + 1) AS NEW_AGE FROM STUDENTS ORDER BY NEW_AGE;

-- ORDER BY with Alias
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 12) AS ANNUAL_SALARY FROM EMPLOYEES ORDER BY ANNUAL_SALARY DESC;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, (PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS ORDER BY TOTAL_VALUE DESC;
SELECT STUDENT_NAME, LENGTH(STUDENT_NAME) AS NAME_LENGTH FROM STUDENTS ORDER BY NAME_LENGTH;
SELECT EMPLOYEE_NAME, (SALARY * 0.10) AS INCREMENTED_SALARY FROM EMPLOYEES ORDER BY INCREMENTED_SALARY DESC;
SELECT PRODUCT_NAME, PRICE, DISCOUNT, (PRICE - DISCOUNT) AS DISCOUNTED_PRICE FROM PRODUCTS ORDER BY DISCOUNTED_PRICE;
SELECT COURSE_NAME, FEES, DISCOUNT, (FEES - DISCOUNT) AS DISCOUNTED_FEES FROM COURSES ORDER BY DISCOUNTED_FEES DESC;

-- ORDER BY with Aggregate Functions
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY EMPLOYEE_COUNT DESC;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT FROM STUDENTS GROUP BY DEPARTMENT ORDER BY STUDENT_COUNT;
SELECT DEPARTMENT, SALARY, ROUND(AVG(SALARY)) AS AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT, SALARY ORDER BY AVERAGE_SALARY DESC;
SELECT DEPARTMENT, SALARY, ROUND(MIN(SALARY)) AS MINIMUM_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT, SALARY ORDER BY MINIMUM_SALARY;
SELECT DEPARTMENT, SALARY, ROUND(MAX(SALARY)) AS MAXIMUM_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT, SALARY ORDER BY MAXIMUM_SALARY;
SELECT DEPARTMENT, SALARY, ROUND(SUM(SALARY)) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT, SALARY ORDER BY TOTAL_SALARY DESC;
SELECT PRODUCT_NAME, PRICE, ROUND(AVG(PRICE)) AS AVERAGE_PRICE FROM PRODUCTS GROUP BY PRODUCT_NAME, PRICE ORDER BY AVERAGE_PRICE DESC;
SELECT PRODUCT_NAME, PRICE, ROUND(MAX(PRICE)) AS MAXIMUM_PRICE FROM PRODUCTS GROUP BY PRODUCT_NAME, PRICE ORDER BY MAXIMUM_PRICE DESC;
SELECT PRODUCT_NAME, PRICE, ROUND(MIN(PRICE)) AS MINIMUM_PRICE FROM PRODUCTS GROUP BY PRODUCT_NAME, PRICE ORDER BY MINIMUM_PRICE;
SELECT PRODUCT_NAME, PRICE, ROUND(SUM(PRICE)) AS TOTAL_PRICE FROM PRODUCTS GROUP BY PRODUCT_NAME, PRICE ORDER BY TOTAL_PRICE;

-- Advanced Practice
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 5;
SELECT PRODUCT_NAME, PRICE FROM PRODUCTS ORDER BY PRICE LIMIT 5;
SELECT TITLE, PRICE FROM BOOKS ORDER BY PRICE DESC LIMIT 3;
SELECT STUDENT_NAME, MARKS FROM STUDENTS ORDER BY MARKS LIMIT 10;
SELECT EMPLOYEE_NAME, EXPERIENCE FROM EMPLOYEES ORDER BY EXPERIENCE DESC LIMIT 5;
SELECT PRODUCT_NAME, PRICE, AVAILABLE_STOCK, (PRICE * AVAILABLE_STOCK) AS TOTAL_VALUE FROM PRODUCTS ORDER BY TOTAL_VALUE DESC LIMIT 5;
SELECT COURSE_NAME, FEES FROM COURSES ORDER BY FEES LIMIT 3;
SELECT TITLE, RATING FROM MOVIES ORDER BY RATING DESC LIMIT 5;
SELECT EMPLOYEE_NAME, JOINING_DATE FROM EMPLOYEES ORDER BY JOINING_DATE DESC LIMIT 5;
SELECT CUSTOMER_NAME, REGISTERED_DATE FROM CUSTOMERS ORDER BY REGISTERED_DATE LIMIT 5;