USE STUDENTDB;
USE EMPLOYEEDB;
USE HOSPITALDB;
USE LIBRARYDB;
USE SHOPPINGDB;
USE COLLEGEDB;
USE ECOMMERCEDB;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS ADD COLUMN MARKS INT;
UPDATE STUDENTS SET MARKS = 98 WHERE STUDENT_ID IN (101, 102, 103, 104);
SET SQL_SAFE_UPDATES=0;

-- Statistical / Aggregate Functions
SELECT COUNT(*) FROM EMPLOYEES;
SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT DEPARTMENT, COUNT(*) AS TOTAL_STUDENTS FROM STUDENTS GROUP BY DEPARTMENT;
SELECT DEPARTMENT, ROUND(AVG(MARKS)) AS AVERAGE_MARKS FROM STUDENTS GROUP BY DEPARTMENT;
SELECT DEPARTMENT, ROUND(MAX(MARKS)) AS HIGHEST_MARKS FROM STUDENTS GROUP BY DEPARTMENT;
SELECT CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES FROM CUSTOMERS GROUP BY CUSTOMER_NAME;
SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCTS GROUP BY CATEGORY;

-- Challenge Questions
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 12) AS ANNUAL_SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 5;
SELECT UPPER(EMPLOYEE_NAME), LENGTH(EMPLOYEE_NAME) AS NAME_LENGTH FROM EMPLOYEES ORDER BY NAME_LENGTH DESC;
SELECT PRODUCT_NAME, ROUND(PRICE, 2) AS ROUNDED_PRICE FROM PRODUCTS ORDER BY PRICE DESC;
SELECT PRODUCT_NAME FROM PRODUCTS ORDER BY PRICE DESC LIMIT 10 OFFSET 10;
SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY AVERAGE_SALARY DESC LIMIT 1;
SELECT EMPLOYEE_NAME, SALARY, (SALARY * 12) AS `ANNUAL SALARY`, ROUND(SALARY, 0) AS `ROUNDED SALARY`,
CASE 
WHEN SALARY >= 50000 THEN 'HIGHLY PAID'
WHEN SALARY >= 40000 THEN 'MEDIIUM PAID'
ELSE 'LOW PAID'
END AS `SALARY CATEGORY`
FROM EMPLOYEES ORDER BY `ANNUAL SALARY` DESC;
