USE EMPLOYEEDB;
USE ECOMMERCEDB;

SELECT UPPER(EMPLOYEE_NAME) AS UPPERCASE FROM EMPLOYEES;
SELECT LOWER(EMPLOYEE_NAME) AS LOWERCASE FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, LENGTH(EMPLOYEE_NAME) AS NAME_LENGTH FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, LEFT(EMPLOYEE_NAME, 3) AS LEFT_NAME FROM EMPLOYEES;
SELECT EMPLOYEE_NAME, RIGHT(EMPLOYEE_NAME, 3) AS RIGHT_NAME FROM EMPLOYEES;
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME FROM EMPLOYEES;
SELECT TRIM(EMPLOYEE_NAME) AS TRIM_NAME FROM EMPLOYEES;
SELECT CITY, REPLACE(CITY, 'CHENNAI', 'MADRAS') AS REPLACED_CITY FROM CUSTOMERS;
