SET SQL_SAFE_UPDATES=0;

-- UPDATE – Single Column
USE STUDENTDB;
SELECT * FROM STUDENTS;
UPDATE STUDENTS SET DEPARTMENT='COMPUTER SCIENCE' WHERE STUDENT_ID=101;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET SALARY=55000.00 WHERE EMPLOYEE_ID='A1441';

USE HOSPITALDB;
SELECT * FROM PATIENTS;
UPDATE PATIENTS SET DISEASE='FEVER' WHERE PATIENT_ID=2;

USE LIBRARYDB;
SELECT * FROM BOOKS;
UPDATE BOOKS SET PRICE=750.00 WHERE BOOK_ID=22;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET PRICE=2500.00 WHERE PRODUCT_ID='F87';

--  UPDATE – Multiple Columns
USE STUDENTDB;
SELECT * FROM STUDENTS;
UPDATE STUDENTS SET AGE=26, DEPARTMENT='COMPUTER SCIENCE' WHERE STUDENT_ID=102;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET DEPARTMENT='BPO', SALARY='250000.00' WHERE EMPLOYEE_ID='D13';

USE HOSPITALDB;
SELECT * FROM PATIENTS;
UPDATE PATIENTS SET PHONE='7097789654', DISEASE='LEG INJUIRY' WHERE PATIENT_ID=4;

USE LIBRARYDB;
SELECT * FROM BOOKS;
UPDATE BOOKS SET AUTHOR='ANTO', PRICE=2500.00 WHERE BOOK_ID=32;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET BRAND='UNKNOWN', PRICE=1500.00 WHERE PRODUCT_ID='F87';

-- UPDATE – Using Conditions
USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET SALARY=SALARY * 1.10 WHERE DEPARTMENT='IT';

USE LIBRARYDB;
SELECT * FROM BOOKS;
UPDATE BOOKS SET PRICE=PRICE * 1.05 WHERE CATEGORY='FANTASY';

USE HOTELDB;
SELECT * FROM ROOMS;
UPDATE ROOMS SET AVAILABILITY='Y' WHERE PRICE_PERDAY<3000;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET DISCOUNT=10.00 WHERE PRICE>5000;

USE MOVIEDB;
SELECT * FROM MOVIES;
UPDATE MOVIES SET RATING=5.0 WHERE GENRE='FAMILY';

-- DELETE – Single Record
USE STUDENTDB;
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS WHERE STUDENT_ID=110;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID='R34';

USE HOSPITALDB;
SELECT * FROM PATIENTS;
DELETE FROM PATIENTS WHERE PATIENT_ID=7;

USE LIBRARYDB;
SELECT * FROM BOOKS;
DELETE FROM BOOKS WHERE BOOK_ID=22;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS WHERE PRODUCT_ID='M4';

--  DELETE – Using Conditions
USE STUDENTDB;
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS WHERE AGE<18;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
DELETE FROM EMPLOYEES WHERE SALARY<25000;

USE HOSPITALDB;
SELECT * FROM PATIENTS;
DELETE FROM PATIENTS WHERE DISEASE='CANCER';

USE LIBRARYDB;
SELECT * FROM BOOKS;
DELETE FROM BOOKS WHERE PRICE<150;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS WHERE AVAILABLE_STOCK=0;

-- DELETE – Multiple Conditions
USE STUDENTDB;
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS WHERE AGE<25 AND DEPARTMENT='BA';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES;
DELETE FROM EMPLOYEES WHERE DEPARTMENT='HR' AND SALARY<30000;

USE HOTELDB;
SELECT * FROM ROOMS;
DELETE FROM ROOMS WHERE AVAILABILITY='N' AND PRICE_PERDAY<2000;

USE MOVIEDB;
SELECT * FROM MOVIES;
DELETE FROM MOVIES WHERE LANGUAGE='TAMIL' AND RATING<3;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS;
DELETE FROM CUSTOMERS WHERE CITY='CHENNAI' OR COUNTRY='NULL';